
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (1,'Porto Alegre','RS','Moinhos de Vento');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (2,'Porto Alegre','RS','Petrópolis');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (3,'Porto Alegre','RS','Centro Histórico');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (4,'Porto Alegre','RS','Menino Deus');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (5,'Porto Alegre','RS','Bela Vista');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (6,'Porto Alegre','RS','Cidade Baixa');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (7,'Caxias do Sul','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (8,'Caxias do Sul','RS','Pelegrino');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (9,'Caxias do Sul','RS','Lourdes');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (10,'Canoas','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (11,'Canoas','RS','Marechal Rondon');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (12,'Pelotas','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (13,'Pelotas','RS','Areal');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (14,'Santa Maria','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (15,'Santa Maria','RS','Camobi');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (16,'Passo Fundo','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (17,'Novo Hamburgo','RS','Hamburgo Velho');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (18,'São Leopoldo','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (19,'Rio Grande','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (20,'Bento Gonçalves','RS','Cidade Alta');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (21,'Erechim','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (22,'Santa Cruz do Sul','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (23,'Gravataí','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (24,'Viamão','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (25,'Encruzilhada do Sul','RS','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (26,'Florianópolis','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (27,'Florianópolis','SC','Trindade');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (28,'Florianópolis','SC','Agronômica');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (29,'Florianópolis','SC','Coqueiros');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (30,'Florianópolis','SC','Campeche');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (31,'Joinville','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (32,'Joinville','SC','América');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (33,'Joinville','SC','Costa e Silva');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (34,'Blumenau','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (35,'Blumenau','SC','Vila Nova');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (36,'Blumenau','SC','Victor Konder');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (37,'Itajaí','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (38,'Itajaí','SC','Fazenda');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (39,'Balneário Camboriú','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (40,'Balneário Camboriú','SC','Barra Sul');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (41,'Chapecó','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (42,'Criciúma','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (43,'Jaraguá do Sul','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (44,'Lages','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (45,'Palhoça','SC','Pagani');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (46,'Brusque','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (47,'Tubaraão','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (48,'São José','SC','Kobrasol');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (49,'Navegantes','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (50,'Gaspar','SC','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (51,'Curitiba','PR','Batel');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (52,'Curitiba','PR','Centro Cívico');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (53,'Curitiba','PR','Água Verde');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (54,'Curitiba','PR','Bigorrilho');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (55,'Curitiba','PR','Portão');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (56,'Curitiba','PR','Jardim das Américas');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (57,'Londrina','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (58,'Londrina','PR','Gleba Palhano');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (59,'Maringá','PR','Zona 01');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (60,'Maringá','PR','Zona 07');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (61,'Ponta Grossa','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (62,'Cascavel','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (63,'Foz do Iguaçu','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (64,'São José dos Pinhais','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (65,'Guarapuava','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (66,'Paranaguá','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (67,'Toledo','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (68,'Arapongas','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (69,'Umuarama','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (70,'Campo Mourão','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (71,'Cambé','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (72,'Fazenda Rio Grande','PR','Eucaliptos');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (73,'Piraquara','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (74,'Pinhais','PR','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (75,'Colombo','PR','Alto Maracanã');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (76,'São Paulo','SP','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (77,'São Paulo','SP','Moema');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (78,'São Paulo','SP','Pinheiros');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (79,'São Paulo','SP','Tatuapé');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (80,'São Paulo','SP','Itaquera');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (81,'São Paulo','SP','Vila Mariana');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (82,'São Paulo','SP','Santana');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (83,'São Paulo','SP','Lapa');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (84,'Campinas','SP','Cambuí');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (85,'Campinas','SP','Barão Geraldo');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (86,'Campinas','SP','Taquaral');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (87,'São José dos Campos','SP','Jardim Aquárius');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (88,'Ribeirão Preto','SP','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (89,'Ribeirão Preto','SP','Zona Sul');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (90,'Sorocaba','SP','Campolim');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (91,'Santos','SP','Gonzaga');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (92,'Santos','SP','Boqueirão');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (93,'Osasco','SP','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (94,'Santo André','SP','Bairro Jardim');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (95,'São Bernardo do Campo','SP','Rudge Ramos');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (96,'Piracicaba','SP','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (97,'Jundiaí','SP','Anhangabaú');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (98,'Bauru','SP','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (99,'Mogi das Cruzes','SP','Centro');
INSERT INTO `` (`id_localidade`,`cidade`,`estado`,`bairro`) VALUES (100,'Guarulhos','SP','Centro');
